## optional for lab or single-node setups where control planes should also run workloads
- name: Remove NoSchedule taint from controlplane
  hosts: controlplanes[0]
  tasks:
  
  - name: Remove controlplane taint
    ansible.builtin.command: 
     cmd: kubectl taint nodes --all node-role.kubernetes.io/control-plane-

  - name: Log taints
    ansible.builtin.command:
      cmd: kubectl get node {{ groups['controlplanes'][0] }} -o jsonpath={.spec.taints[*].key}
    register: controlplane_taints
    changed_when: false

  - name: Check taint removed from controlplane node
    ansible.builtin.assert:
      that:
        - "'node-role.kubernetes.io/control-plane' not in controlplane_taints.stdout"
      fail_msg: "Node is still tainted"
